### ISSUE TITLE
Where's the atom feed? 

### ISSUE THREAD

**Issue by DarkLinkXXXX** [doar-e/doar-e.github.io#1]
I swear there was a working atom feed a few days ago. Now the part of your html that's supposed to link to an atom feed just links to the root of your website. https://github.com/doar-e/doar-e.github.io/blob/master/index.html#L46

**Comment by 0vercl0k** [comment]
Oh that's a great point - I have recently migrated the blog from octopress
to pelican and I didn't think about setting one up for pelican. Let me look
into that this week!

Cheers

2018-03-15 13:13 GMT-07:00 DarkLinkXXXX <notifications@github.com>:

**Comment by 0vercl0k** [comment]
All right I changed the configuration to output a variety of feeds, they
are all available here:
https://github.com/doar-e/doar-e.github.io/tree/master/feeds.

Let me know if you need anything else :).

Cheers

2018-03-17 10:52 GMT-07:00 0vercl0k <0vercl0k@tuxfamily.org>:
